In [89]:
# 리스트 구조
l =[[1,2,3,],[4,5,6]]
type(l)


list

In [90]:
# 리스트 내의 원소는 index 라는 정보를 가진다
l[0]


[1, 2, 3]

In [91]:
l[1]

[4, 5, 6]

In [92]:
# 리스트내의 리스트 검색
for i, a in enumerate(l) : 
    for j,b in enumerate(a) :
        print(l[i][j])

1
2
3
4
5
6


In [93]:
#다차원 배열 구조
import numpy as np

In [94]:
np.__version__

'1.26.4'

In [95]:
#  다차원 배열 클래스  ndarray  --> 배열하다
print(np.ndarray)

<class 'numpy.ndarray'>


In [96]:
np.ndarray.__name__


'ndarray'

In [97]:
for i in dir (np.ndarray) :
    if not i. startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [98]:
# 다차원 배열 만들기
l=[1,2,3,4]
a=np.array(l)

In [99]:
a


array([1, 2, 3, 4])

In [100]:
type(a)

numpy.ndarray

In [101]:
t=(1,2,3,4)
b= np.array(t)


In [102]:
type(b)

numpy.ndarray

In [103]:
# 다차원 배열 데이터 관리
a.data

In [104]:
a.data.obj

array([1, 2, 3, 4])

In [105]:
type(a.data.obj)


numpy.ndarray

In [106]:
# 다차원 배열  자료형 관리   array 

e=np.array(l, dtype=np.float64)
e

array([1., 2., 3., 4.])

In [107]:
e.dtype

dtype('float64')

In [108]:
# 2 차원 배열의 정보 확인
# 형태(shape)
# 차원(ndim)
# 하나의 원소크기(itemsize)
# 전체 원소의 개수 (size)
# 원소와 하나의 행의 바이트 크기(strides) 

a2 = np.array([[1,2,3,],[4,5,6]])
a2.shape


(2, 3)

In [109]:
a2.ndim   # 차원

2

In [110]:
a2.dtype  #

dtype('int32')

In [111]:
a2.itemsize #하나의 원소크기

4

In [112]:
a2.size # 전체원소의 개수 

6

In [113]:
a2.strides  #원소와 하나의 행 바이트 크기

(12, 4)

###  다차원 배열의 구조
- • 두 개의 다차원 배열을 지원합니다. 차이점은 Matrix는 행렬을 처리만 지원합니다.
- • 클래스의 상속관계를 확인하면 matrix 클래스는 ndarray를 상속해서 처리합니다. 



In [114]:
np.ndarray.__bases__

(object,)

In [115]:
np.matrix.__bases__

(numpy.ndarray,)

### 넘파이 모듈의 함수 특징

In [116]:
# 넘파이 모듈은 동일한 기능을 가진 함수와 메소드를 제공합니다.
(a != 0 ).any

<function ndarray.any>

In [117]:
np.any

<function any at 0x0000024D987FBAF0>

In [118]:
np.ndarray.any is np.core.fromnumeric.any

False

In [119]:
# 같은 이름의 함수와 메소드-----------------------------------
np_=set(dir(np))

In [120]:
nd_= set(dir(np.ndarray))

In [121]:
npd_= np_& nd_

In [122]:
len(npd_)

48

In [123]:
count=0
for i in list (npd_):
    count +=1
    print(i, end = "")
    if count % 5 ==0 :
        print()

prodnbytesstdsqueezeswapaxes
tracedtypetakeminsort
ndimimagshapesizenonzero
argsortmaxdot__doc__all
argmaxtransposecumprodanysearchsorted
__dir__chooseclipargminptp
raveldiagonalputcopyconj
conjugatepartitionsumreshapemean
resizecompressargpartitionrealcumsum
roundrepeatvar

In [124]:
#  유니버셜 함수 -----------------
# 넘파이 특징은 반복문을 사용하지 않는 계산입니다. 이런 기능을 벡터화 연산이라고하며 이를 지원하는 함수가 유니버셜 함수입니다. 

In [125]:
a= dir(np)

In [126]:
np.ufunc

numpy.ufunc

In [127]:
# 백터화 연산----------------------------------------------------
# • 4개의 원소를 가지는 두 개의 배열을 만듭니다. 이 두 배열의 곱셈을 수행할 때 별도의 반복하는 코드가 필요없습니다. 
# • 벡터화연산은 배열의 같은 위치의 원소끼리 계산을 자동으로 처리하는 기능입니다.

In [128]:
a= np.arange(6,10)  # range 랑 비슷
a
# 2부터 10까지 2씩 증가하는 배열 생성---
# arr = np.arange(2, 10, 2)
# numpy.arange([start, ]stop, [step, ], dtype=None)---
# start: 배열의 시작 값을 지정합니다. (포함, 기본값은 0)
# stop: 배열의 마지막 값으로, 이 값은 포함되지 않습니다.
# step: 배열의 요소 간의 간격을 지정합니다. 기본값은 1입니다.
# dtype: 출력 배열의 데이터 타입을 지정합니다. 지정하지 않으면 입력에 따라 자동으로 설정됩니다.

array([6, 7, 8, 9])

In [129]:
b= np.arange(10,14)
b

array([10, 11, 12, 13])

In [130]:
c= a* b 
c 

array([ 60,  77,  96, 117])

###  축 연산

 

In [131]:
# • 1차원 배열을 만들고 2차원 배열로 변경한 후에 sum을 수행하면 전체의 원소를 합산합
# 니다.
# • 2차원 배열은 두개의 축을 가지므로 각 축별로 계산이 가능합니다.

In [132]:
a2 = np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [133]:
a2 = a2.reshape(2,2)  #reshape 모양을 고치다
a2

array([[1, 2],
       [3, 4]])

In [134]:
np.sum(a2)

10

In [135]:
np.sum(a2,axis =0 )


array([4, 6])

In [136]:
# 배열의 원소 개수 일치-----------------
# • 벡터화연산을 처리할 때 두 배열의 원소의 개수가 일치가 아주 중요합니다. 
# • 원소의 개수가 다른 경우는 shape가 다르다는 에러가 발생합니다.


In [137]:
a = np.array([4,5])
a.shape

(2,)

In [138]:
b =  np.array([3,4,6])
b.shape

(3,)

In [139]:
try :
    a+b
except Exception as e :
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


## 배열 할당과 검색

In [140]:
# 배열을 다른 변수에 할당
# • 다차원 배열을 다른 변수에 할당하면 공유 즉 동일한 뷰를 제공합니다.
# • 특정 원소를 갱신하면 원본이 갱신됩니다.

In [141]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [142]:
b = a
b

array([[1, 2],
       [3, 4]])

In [143]:
b[0] =999

In [144]:
a

array([[999, 999],
       [  3,   4]])

In [145]:
b


array([[999, 999],
       [  3,   4]])

In [146]:
#  배열의 복사 / 뷰 확인
# • 새로운 다차원 배열로 사용하려면 copy 메소드를 사용해 다른 변수에 할당합니다.
# • 다차원 배열을 슬라이스해도 뷰이므로 동일한 배열을 공유합니다. 

In [147]:
f = np.array ([4,5,6,7,8])
e = f.copy()

In [148]:
f

array([4, 5, 6, 7, 8])

In [149]:
e

array([4, 5, 6, 7, 8])

In [150]:
g = f[:]

In [151]:
g.base  # 베이스 

array([4, 5, 6, 7, 8])

In [152]:
np.may_share_memory(g,f)

True

In [153]:
# 리스트 검색 ------------------------------
# • 검색 기호는 대괄호([ ])이며 이 기호가 실행되면 내부적으로 __getitem__ 스페셜 메소드가 실행되는 것입니다.
# • 슬라이스도 검색 기호에 slice 객체를 인자로 전달해 검색합니다. 

In [154]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [155]:
index = 1


In [156]:
l.__getitem__(index)

2

In [157]:
l[1]

2

In [158]:
index =  slice(1,3)  #  슬라이스

In [159]:
l.__getitem__(index)

[2, 3]

In [160]:
# 다차원 배열 검색 ----------------------------
# 리스트와 동일한 방식으로 검색을 처리 합니다.


In [161]:
a =  np.array([1,2,3,4,5,6,7])


In [162]:
index =1 

In [163]:
a.__getitem__(index)

2

In [166]:
index = slice(1,3)

In [168]:
a.__getitem__(index)

array([2, 3])

In [172]:
#• 다차원 배열은 검색할 때 배열을 인자로 전달해서 검색이 가능합니다 .
#• 배열을 정수나 논리 값으로 넣고 처리가 가능합니다. 

In [177]:
index = 1
# a =  np.array([1,2,3,4,5,6,7]) 

In [174]:
a.__getitem__(index)    

2

In [178]:
index=[1]

In [ ]:
a.__getitem__