In [126]:
import numpy as np
import pandas as pd

In [127]:
# 소수점 이하 3자리로 제한
%precision 3

'%.3f'

In [128]:
# # DataFrame 의 출력을 소수점 이하 3자리로 제한
# pd.set_option('precision', 3)

In [129]:
#  2, 3장에서 사용하는 데이터(50명 학생의 영어, 수학 점수)

df =  pd.read_csv(r'C:\Users\LG\Desktop\교수님\DAY1\ch2_scores_em.csv',index_col ='student number')
df.head()


english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [130]:

# 학번 순서대로 10명의 영어 점수를 array 데이터 구조 scores에 저장
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [131]:
scores_df = pd.DataFrame({'score' : scores}, 
                         index =pd.Index(['A','B','C','D','E','F','G','H','I','j'],name = 'student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
j           58

### 평균값

In [132]:

#평균값은 데이터를 모두 더한뒤, 데이터의 개수로 나누어 구함
sum(scores)/len(scores)


55.000

In [133]:
np.mean(scores)

55.000

In [134]:
scores_df.mean()

score    55.0
dtype: float64

### 중앙값

In [135]:
# • 중앙값은 데이터를 크기 순서대로 나열할 때 정확히 중앙에 위치한 값-이상값에 영향을 덜 받음
 # 정렬 후 코드 작성 및 실행
sorted_scores = np.sort(scores)
sorted_scores



array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [136]:
n= len(sorted_scores)
if n % 2 == 0 :
    m0 = sorted_scores[n//2-1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1)/2
else :
    median = sorted_scores[(n+1)//2-1]
median

56.500

### 최빈값


In [137]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

### 분산과 표준편차

In [138]:
#편차

# ◦ 각 데이터가 평균으로부터 떨어져 있는 정도
# ◦ 각 학생의 성적 편차

mean = np.mean(scores)
deviation=  scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [139]:
# 편차 비교
#◦ 10명의 편찻값으로 비교가 어려우므로, 하나의 값인 편차 평균 비교
#◦ 편차 평균은 0
summary_df = scores_df.copy()
summary_df['deviation'  ]= deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
j           58        3.0

In [140]:
summary_df.mean()


score        55.0
deviation     0.0
dtype: float64

In [141]:
# 분산 
# ◦ 산포도의 지표인 편차의 평균은 항상 0
# ◦ 앞의 B 학생과 D 학생은 모두 평균에서 14점 떨어져 동일 정도의 산포도를 가지지만, 단순히 더하면 서로 상쇄
# 되어 0이 되므로 편차의 제곱을 이용
# ◦ 편차 제곱의 평균이 분산(모분산)

np.mean(deviation ** 2)


86.000

In [142]:
np.var(scores)

86.000

In [143]:
# 분산 
# 표본분산

# ◦ Pandas는 DataFrame이나 Series의 var 메서드는 불편분산 (10장)
# ◦ Pandas의 표본분산은 var 메서드의 인수 ddof=0
scores_df.var()



score    95.555556
dtype: float64

In [145]:
# 분산 Nunpy 로 분산 계산 / summary_df 에 편차의 재곱 열 추가
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
j           58        3.0                  9.0

In [146]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [ ]:
#[25]
np.sqrt(np.var(scores))