In [7]:
import numpy as np
#173

### 균등분포
- 이산분포를 처리하는 randint 함수에 인자로 이산된 정수의 값을 두 개 지정합니
다. 또한 만들어질 배열의 크기를 size 매개변수에 지정합니다.
- 균등분포 함수에도 시작 값과 종료 값을 넣어서 배열을 생성할 수 있는 uniform 
함수도 있습니다. 0과 1을 지정해서 균등분포를 만들 수도 있습니다

In [ ]:
x =  np.random.randint(3,10,size=10)
x

In [3]:
y =  np.random.randint(3,10, size = (3,3))
y

array([[7, 7, 6],
       [6, 7, 4],
       [5, 7, 8]])

In [4]:
x= np.random.uniform(0,1,10)
x

array([0.64571161, 0.80058797, 0.62622675, 0.84700433, 0.59479628,
       0.13877697, 0.4828167 , 0.16898322, 0.24679328, 0.56169738])

In [5]:
y= np.random.uniform(10,20,(3,3))
y

array([[19.378427  , 19.51475627, 11.79925243],
       [16.60601873, 18.21809625, 14.49530403],
       [15.17773759, 15.79236828, 16.06974411]])